# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 嵇爾的吐槽
email: nightghostjiyou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  没事画轮子的嵇尔不定期的(W)碎(E)碎(B)念(B)和(L)吐(O)槽(G)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jithee.com" # the base hostname & protocol for your site
github_username:  JiYouMCC
# Build settings
markdown: kramdown
permalink: /blog/post/:title/
paginate: 7
paginate_path: "/blog/index/:num"
gems: [jekyll-paginate]
excerpt_separator: <!--more-->