title: 嵇爾的吐槽
email: nightghostjiyou@gmail.com
description: 没事画轮子的嵇尔不定期的(W)碎(E)碎(B)念(B)和(L)吐(O)槽(G)
baseurl: "" 
url: "http://www.jithee.name"
github_username:  JiYouMCC
# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /blog/post/:title/
paginate: 7
paginate_path: "/blog/index/:num"
gems: [jekyll-paginate]
excerpt_separator: <!--more-->
timezone: Asia/Shanghai
