title: 嵇爾的吐槽
email: chengyi.ye+githubio@outlook.com
description: 没事画轮子的嵇尔不定期的(W)碎(E)碎(B)念(B)和(L)吐(O)槽(G)
baseurl: "" 
author: "嵇尔"
url: "https://jiyoumcc.github.io"
github_username:  JiYouMCC
# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /blog/post/:title/
paginate: 7
paginate_path: "/blog/index/:num"
gems: 
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
excerpt_separator: <!--more-->
timezone: Asia/Shanghai
defaults:
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
  - scope:
      path: "photo"
    values:
      photo: true
exclude: [vendor]
plugins: 
  - jekyll-paginate