name: npx test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: mikeal/npx@master
    - run: npx -y pagefind --site public --serve
